### ISSUE TITLE
publish docker images to hub.docker.com

### ISSUE THREAD

**Issue by shawphy** [nkanaev/yarr#20]
Would you please publish docker images to hub.docker.com?
thx.

**Comment by LyleLee** [comment]
Looks like some extra work need to do:
```
root@vm:~/github/yarr# docker build -t yarr .
Sending build context to Docker daemon    4.8MB
Step 1/10 : FROM golang:alpine AS build
 ---> 6af5835b113c
Step 2/10 : RUN apk add build-base git
 ---> Using cache
 ---> edeb0fd3ebc2
Step 3/10 : WORKDIR /src
 ---> Using cache
 ---> c1948d407e50
Step 4/10 : COPY . .
 ---> Using cache
 ---> 78ff25d7fe88
Step 5/10 : RUN make build_linux
 ---> Running in 6ec686196522
go run scripts/bundle_assets.go >/dev/null
go: github.com/mmcdole/gofeed@v1.0.0: parsing gofeed/go.mod: open /src/gofeed/go.mod: no such file or directory
make: *** [makefile:13: server/assets.go] Error 1
The command '/bin/sh -c make build_linux' returned a non-zero code: 2
root@vm:~/github/yarr#

```

**Comment by LyleLee** [comment]
This happened  because https://github.com/nkanaev/yarr/commit/2b3045f773c334a746562ca45589f9fd8750b3f5 replace github.com/mmcdole/gofeed => ./gofeed, and modified gofeed is not on the repo.

**Comment by eldridgea** [comment]
If anyone wants to test my PR's autodeploy, I have my fork pushing to dockerhub as `eldridgea/yarr`

**Comment by nkanaev** [comment]
@LyleLee @eldridgea the reason the build failed is because `gofeed` is missing in the project root directory (the process is documented [here](https://github.com/nkanaev/yarr/blob/63b265fa049687a94aded07f88dbe7c5c509cac4/doc/hacking.md#build)).

as stated earlier in https://github.com/nkanaev/yarr/pull/30#issuecomment-762161658, the upstream project still has a couple patches on master not semantically versioned.

**Comment by nkanaev** [comment]
@eldridgea unfortunately i don't have an account on dockerhub (nor willing to). i can configure your credentials or give you access to the repo if you'd like to though.

**Comment by bejonwe** [comment]
Saw your post Reddit and wanted to give it a try, but ran into the gofeed problem. Maybe adding `RUN git clone https://github.com/nkanaev/gofeed.git` would be a good fix? I added the line to the dockerfile and the build now works like a charm. Here is my dockerfile and my docker-compose.yml file:

```
FROM golang:alpine AS build
RUN apk add build-base git
WORKDIR /src
COPY . .
RUN git clone https://github.com/nkanaev/gofeed.git
RUN make build_linux

FROM alpine:latest
RUN apk add --no-cache ca-certificates && \
    update-ca-certificates
COPY --from=build /src/_output/linux/yarr /usr/local/bin/yarr
EXPOSE 7070
CMD ["/usr/local/bin/yarr", "-addr", "0.0.0.0:7070", "-db", "/data/yarr.db"]
```

```
version: "2"
services:
  web:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yarr.rule=Host(`...`)"
      - "traefik.http.routers.yarr.tls=true"
      - "traefik.http.routers.yarr.tls.certresolver=default"
    volumes:
      - ./data:/data
```
