### ISSUE TITLE
dial tcp: i/o timeout

### ISSUE THREAD

**Issue by Brancliff** [nkanaev/yarr#89]
Hey! I tried out yarr for Windows, and I like its simplicity - it seems like it has everything I need, but I'm having trouble when switching over to the docker version.

I can't get any feeds - whenever I try anything (obligatory example url: https://www.reddit.com/r/catsnamedafterfood/.rss ), I just get a popup saying it couldn't find anything. But I do get this line in my container console:

2022/02/13 06:33:31 routes.go:210: Faild to discover feed for https://www.reddit.com/r/catsnamedafterfood/.rss: Get "https://www.reddit.com/r/catsnamedafterfood/.rss": dial tcp: i/o timeout

I'm wondering if I missed something really obvious here, because I couldn't find that error anywhere on anyone else's issues. Admittedly, I'm not great with linux and still pretty new to docker, so just in case this is it, here's my docker-compose text:

```
version: '2.1'
services:
  yarr:
    image: arsfeld/yarr:latest ## I will also note I did try a few other people's dockerhub pages, but the problem seems to be the same
    container_name: yarr
    volumes:
      - /share/CE_CACHEDEV1_DATA/Library/Projects/Yarr:/data/
    ports:
      - 3010:7070
    restart: unless-stopped
```
